export { default as Admin} from "./Admin"
export { default as Login} from "./Login"
export { default as Logout} from "./Logout"
export { default as RegisterModal} from "./RegisterModal"
export { default as Home} from "./Home"
export { default as Games} from "./Games"
export { default as SingleGame} from "./SingleGame"
export { default as Checkout} from "./Checkout"
